from decouple import config


SLACK_BOT_TOKEN = config("SLACK_BOT_TOKEN")
SLACK_CLIENT_ID = config("SLACK_CLIENT_ID")
SLACK_CLIENT_SERCRET = config("SLACK_CLIENT_SERCRET")
SLACK_VERIFICATION_TOKEN = config("SLACK_VERIFICATION_TOKEN")
