from decouple import config


MONGO_CONNECTION_URL = config("MONGO_CONNECTION_URL")

SLACK_BOT_TOKEN = config("SLACK_BOT_TOKEN")
SLACK_CLIENT_ID = config("SLACK_CLIENT_ID")
SLACK_CLIENT_SERCRET = config("SLACK_CLIENT_SERCRET")
SLACK_VERIFICATION_TOKEN = config("SLACK_VERIFICATION_TOKEN")

COMMAND_MIN_MATCH_RATIO = 80
SAME_WORD_MIN_MATCH_RATIO = 90
